apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fast-api
  name: fast-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fast-api
    spec:
      containers:
      - image: rahul1024/fast-api
        name: fast-api
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "4000Mi"
            cpu: "4000m"
        volumeMounts:
          - mountPath: /root/staging.env
            subPath: staging.env
            name: env
      volumes:
        - name: env
          configMap:
            name: fast-api-config
            items:
              - key: staging.env
                path: staging.env
status: { }
