apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fast-api
  name: fast-api
spec:
  ports:
  - port: 8980
    protocol: TCP
    targetPort: 8980
  selector:
    app: fast-api
  type: ClusterIP
status:
