apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-world
  name: hello-world
spec:
  ports:
  - port: 8980
    protocol: TCP
    targetPort: 8980
  selector:
    app: hello-world
  type: ClusterIP
status:
